In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/yashu/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Anaconda (anaconda3)/creditcard.csv")

In [4]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [8]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [10]:
df.Class.value_counts(dropna=False)

Class
0    284315
1       492
Name: count, dtype: int64

In [12]:
## Independent and dependent features
x = df.iloc[:,:-1]
print(x)
y = df.iloc[:, -1]
print(y)

            Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.25141

###Cross Validation: KFold and Hyperparameter Technique: GridSearchCV

In [15]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [17]:
log_reg = LogisticRegression()
grid = { 'solver': ['liblinear', 'saga'] , "C" : 10.0 ** np.arange(-2,3) , "penalty" : ["l1" , "l2"]}
cv = KFold(n_splits = 5 , random_state = None , shuffle = False )

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(x)

In [21]:
x_train , x_test , y_train , y_test = train_test_split(X,y,test_size=0.25)
print(x_train.shape , y_train.shape)
print(x_test.shape , y_test.shape)

(213605, 30) (213605,)
(71202, 30) (71202,)


In [23]:
clf = GridSearchCV(log_reg , grid, cv =cv , n_jobs=-1 , scoring = "f1_macro")
clf.fit(x_train , y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2'],
                         'solver': ['liblinear', 'saga']},
             scoring='f1_macro')

In [27]:
y_pred = clf.predict(x_test)
print(accuracy_score(y_test , y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test , y_pred))

0.9990309260975815
[[71053    10]
 [   59    80]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71063
           1       0.89      0.58      0.70       139

    accuracy                           1.00     71202
   macro avg       0.94      0.79      0.85     71202
weighted avg       1.00      1.00      1.00     71202



In [29]:
class_weigh = dict({ 0 : 1 , 1 : 100})

In [31]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(class_weight = class_weigh)
rfc.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [33]:
y_pred1 = rfc.predict(x_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test , y_pred1))

0.9993820398303418
[[71060     3]
 [   41    98]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71063
           1       0.97      0.71      0.82       139

    accuracy                           1.00     71202
   macro avg       0.98      0.85      0.91     71202
weighted avg       1.00      1.00      1.00     71202



### UNDER SAMPLING

In [86]:
from imblearn.under_sampling import NearMiss
from collections import Counter

In [113]:
ns = NearMiss(sampling_strategy=0.8)
x_train_ns , y_train_ns = ns.fit_resample(x_train , y_train)
print("The number of y_train cases before fit {} ".format(Counter(y_train)))
print("The number of y_train_ns cases after fit {} ".format(Counter(y_train_ns)))

The number of y_train cases before fit Counter({0: 213252, 1: 353}) 
The number of y_train_ns cases after fit Counter({0: 441, 1: 353}) 


In [115]:
print(y_train.value_counts())
print(y_train_ns.value_counts())

Class
0    213252
1       353
Name: count, dtype: int64
Class
0    441
1    353
Name: count, dtype: int64


In [117]:
ns_rfc = RandomForestClassifier()
ns_rfc.fit(x_train_ns , y_train_ns)
y_pred_ns = ns_rfc.predict(x_test)

In [119]:
print(accuracy_score(y_test , y_pred_ns))
print(confusion_matrix(y_test , y_pred_ns))
print(classification_report(y_test , y_pred_ns))

0.05683829105923991
[[ 3909 67154]
 [    1   138]]
              precision    recall  f1-score   support

           0       1.00      0.06      0.10     71063
           1       0.00      0.99      0.00       139

    accuracy                           0.06     71202
   macro avg       0.50      0.52      0.05     71202
weighted avg       1.00      0.06      0.10     71202



### OVER SAMPLING

In [128]:
from imblearn.over_sampling import RandomOverSampler

In [132]:
os = RandomOverSampler(sampling_strategy = 0.5)
x_train_os , y_train_os = os.fit_resample(x_train , y_train)
print("The number of classes before fit {} ".format(Counter(y_train)))
print("The number of classes after fit {} ".format(Counter(y_train_os)))

The number of classes before fit Counter({0: 213252, 1: 353}) 
The number of classes after fit Counter({0: 213252, 1: 106626}) 


In [140]:
print(y_train.value_counts())
print(y_train_os.value_counts())

Class
0    213252
1       353
Name: count, dtype: int64
Class
0    213252
1    106626
Name: count, dtype: int64


In [136]:
os_rfc = RandomForestClassifier()
os_rfc.fit(x_train_os,y_train_os)
y_pred_os = os_rfc.predict(x_test)

In [145]:
print(accuracy_score(y_test , y_pred_os))
print(confusion_matrix(y_test , y_pred_os))
print(classification_report(y_test , y_pred_os))

0.9993820398303418
[[71058     5]
 [   39   100]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71063
           1       0.95      0.72      0.82       139

    accuracy                           1.00     71202
   macro avg       0.98      0.86      0.91     71202
weighted avg       1.00      1.00      1.00     71202



###SMOTETomek###

In [151]:
from imblearn.combine import SMOTETomek

In [161]:
so = SMOTETomek(sampling_strategy=0.5)
x_train_so , y_train_so = so.fit_resample(x_train , y_train)
print("The number of classes before resampling {} ".format(Counter(y_train)))
print("The number of classes after resampling {}".format(Counter(y_train_so)))

The number of classes before resampling Counter({0: 213252, 1: 353}) 
The number of classes after resampling Counter({0: 213252, 1: 106626})


In [163]:
so_rfc = RandomForestClassifier()
so_rfc.fit(x_train_so , y_train_so)


RandomForestClassifier()

In [164]:
y_pred_so = so_rfc.predict(x_test)
print(accuracy_score(y_test,y_pred_so))
print(confusion_matrix(y_test , y_pred_so))
print(classification_report(y_test , y_pred_so))

0.9994663071262043
[[71053    10]
 [   28   111]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71063
           1       0.92      0.80      0.85       139

    accuracy                           1.00     71202
   macro avg       0.96      0.90      0.93     71202
weighted avg       1.00      1.00      1.00     71202

